### ISSUE TITLE
Linking to same page doesn't close menu

### ISSUE THREAD

**Issue by paulzz3000** [balzss/luxbar#37]
I have anchors linking to sections on the same page but the menu stays open when the links are clicked.
https://carlislepassionplay.org/

**Comment by balzss** [comment]
Please refer to #34. I think you want to achive the same thing.

**Comment by paulzz3000** [comment]
Thanks @balzss 
It works the first time a link is clicked but not a second
Thanks anyway—awesome menu.

**Comment by balzss** [comment]
Basically (because it is pure CSS) the open and the closed state depends on whether a checkbox (which is part of the html snippet you inserted as the menu bar) is checked or not. The reason for the menu closing when you go to a different page is because you load the whole thing "freshly" with the checkbox unchecked. So in order to close it on an item click you have to include some javascript code which programatically "flips" the checkbox's state. To debug this you should also look at the inspected element and see if it's doing what you wanted. I also suggest to do it in vanilla js instead:
```javascript
document.querySelectorAll('.luxbar-item').forEach(function(e) {
    e.addEventListener('click', function() {
        document.querySelector('#luxbar-checkbox').checked = false;
    });
});
```

**Comment by paulzz3000** [comment]
Absolutely brilliant. Thank you so much. Works a charm.
